"use client";

import {
  Upload,
  Zap,
  CheckCircle,
  XCircle,
  BadgeAlert,
  Loader2,
  ShieldAlert,
  Calendar,
  CheckCircle2,
  AlertTriangle,
  FileCheck,
  Search,
  ExternalLink
} from "lucide-react";
import { useState } from "react";

export default function TenderAnalyzer() {
  const [analyzing, setAnalyzing] = useState(false);

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-white mb-2">Tender Analyzer</h1>
        <p className="text-white/40">LLM-Powered Compliance & Risk Deep Dive</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1 space-y-6">
           <div className="p-8 glass rounded-2xl border-2 border-dashed border-white/10 flex flex-col items-center justify-center text-center space-y-4 hover:border-orange-500/30 transition-all cursor-pointer group">
              <div className="p-4 rounded-full bg-white/5 group-hover:bg-orange-500/10 transition-all">
                <Upload className="w-8 h-8 text-white/20 group-hover:text-orange-500" />
              </div>
              <div>
                <p className="text-sm font-bold text-white">Upload Tender Document</p>
                <p className="text-[10px] text-white/40 uppercase mt-1">PDF, DOCX up to 50MB</p>
              </div>
           </div>

           <button
             onClick={() => setAnalyzing(true)}
             className="w-full bg-gradient-to-r from-orange-600 to-orange-500 py-4 rounded-xl font-bold flex items-center justify-center gap-2 hover:shadow-lg hover:shadow-orange-500/20 transition-all text-white"
           >
             {analyzing ? <Loader2 className="w-5 h-5 animate-spin" /> : <Zap className="w-5 h-5 fill-current" />}
             Run Compliance Check
           </button>

           <div className="p-6 glass rounded-2xl border border-white/5 space-y-4">
              <h3 className="text-xs font-bold text-white/40 uppercase">Pre-scan Summary</h3>
              <div className="space-y-3">
                 {[
                   { label: "Tax Clearance", status: "found", icon: CheckCircle, color: "text-green-500" },
                   { label: "RC Number", status: "found", icon: CheckCircle, color: "text-green-500" },
                   { label: "PENCOM Cert", status: "missing", icon: XCircle, color: "text-red-500" },
                   { label: "ITF Compliance", status: "found", icon: CheckCircle, color: "text-green-500" },
                 ].map((item, i) => (
                   <div key={i} className="flex justify-between items-center bg-white/5 px-3 py-2 rounded-lg">
                      <span className="text-xs text-white/60 font-medium">{item.label}</span>
                      <item.icon className={`w-4 h-4 ${item.color}`} />
                   </div>
                 ))}
              </div>
           </div>
        </div>

        <div className="lg:col-span-2 space-y-6">
           <div className="p-8 glass rounded-2xl border border-white/5 min-h-[500px] relative overflow-hidden">
              <div className="flex justify-between items-start mb-8">
                 <div>
                    <h2 className="text-xl font-bold text-white">Analysis Report</h2>
                    <p className="text-sm text-white/40 italic">Generated by GPT-4 Vision + RAG</p>
                 </div>
                 <div className="p-2 border border-orange-500/20 rounded bg-orange-500/5 text-[10px] font-black text-orange-500 uppercase">
                    Risk Level: Medium
                 </div>
              </div>

              {!analyzing ? (
                <div className="space-y-8 animate-in fade-in duration-700">
                   <section className="space-y-3">
                      <h3 className="text-xs font-bold text-orange-500 uppercase flex items-center gap-2">
                         <BadgeAlert className="w-4 h-4" />
                         Critical Findings
                      </h3>
                      <div className="p-4 bg-red-500/5 border border-red-500/10 rounded-xl space-y-2">
                         <p className="text-sm text-white leading-relaxed font-medium">
                           &quot;The tender document specifies a delivery period of 60 days, while the technical proposal indicates 90 days. This creates a high risk of disqualification during evaluation.&quot;
                         </p>
                      </div>
                   </section>

                   <section className="space-y-3">
                      <h3 className="text-xs font-bold text-green-500 uppercase flex items-center gap-2 font-black">
                         Positive Indicators
                      </h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                         <div className="p-4 bg-green-500/5 border border-green-500/10 rounded-xl">
                            <p className="text-white/60 font-bold mb-1">Price Competitiveness</p>
                            <p className="text-white">Estimated score: 8.5/10 based on local material index.</p>
                         </div>
                         <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                            <p className="text-white/60 font-bold mb-1">Local Content</p>
                            <p className="text-white">Full compliance with NCDMB guidelines detected.</p>
                         </div>
                      </div>
                   </section>

                   <section className="p-6 bg-white/2 rounded-2xl border border-white/5">
                      <h3 className="text-xs font-bold text-white/40 uppercase mb-4">Recommended Adjustments</h3>
                      <ul className="space-y-3">
                         {[
                           "Re-calibrate the delivery timeline to 60 days to match specs.",
                           "AI Scan detected missing safety indemnity clause in Section 4.2. Recommended action: Insert standard 'Lagos Construction Safety Annex B'"
                         ].map((text, i) => (
                           <li key={i} className="flex gap-3 text-sm text-white/80">
                              <span className="text-orange-500 font-bold">0{i+1}.</span>
                              {text}
                           </li>
                         ))}
                      </ul>
                   </section>
                </div>
              ) : (
                <div className="absolute inset-0 flex flex-col items-center justify-center space-y-6">
                   <div className="w-20 h-20 border-4 border-orange-500/20 border-t-orange-500 rounded-full animate-spin" />
                   <div className="text-center">
                      <p className="text-white font-bold animate-pulse text-lg">Scanning for Compliance...</p>
                      <p className="text-white/40 text-xs mt-1">Cross-referencing with Federal Procurement Act 2007</p>
                   </div>
                </div>
              )}
           </div>
        </div>
      </div>
    </div>
  );
}
